platform :ios, '8.0'

target ‘LLPlayer’ do
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'WebViewJavascriptBridge', '~> 4.1.4'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'YYAsyncLayer', '~> 1.0'
pod 'SSKeychain', '~> 1.4.0'
pod 'YYModel', '~> 1.0.3'
pod 'Masonry','1.0.1'
pod 'BlocksKit'

pod 'UMengSocialCOM', '~> 5.2.1'
pod 'UMengAnalytics', '~> 4.0.4'
pod 'JPush-iOS-SDK', '~> 2.1.8'

end
